### ISSUE TITLE
Support for Roll Public API's

### ISSUE THREAD

**Issue by marlon-wiprud** [TuringAdvisoryGroup/tryrolljs#200]
Add support for all the api's described in this document: https://github.com/TuringAdvisoryGroup/documentation/blob/master/api-design/api-design-document.md

Note that these endpoints must support the authentication mechanisms listed in the doc.

**Comment by ParminderQA** [comment]
I have verified the functionality and it's working fine as referred video provided by Diego under this [Pull 216](https://github.com/TuringAdvisoryGroup/tryrolljs/pull/216) on the QA environment

![image](https://user-images.githubusercontent.com/105701190/235700129-47b8ebb3-445e-41ce-87eb-a82e66fed772.png)
